#!/bin/sh

maprbox_help() {
  cat << EOF
Usage: $0 command

Common commands:
   help        shows this help

   init        installs puppet, r10k, and puppet modules
   setup       install and configure MapR cluster node

   start       start mapr zookeeper and warden
   stop        stop mapr warden and zookeeper
   restart     restart mapr zookeeper and warden
   remove      remove mapr packages and /opt/mapr

   up          init + setup + start
   clean       stop + remove
EOF
}

maprbox_init() {
	DIR=$(dirname $0)

	# install puppet repo
	sudo rpm -Uvh https://yum.puppetlabs.com/puppet5/puppet5-release-el-7.noarch.rpm

	# install puppet agent
	sudo yum install -y puppet-agent

	# install r10k from Ruby Gems
	sudo /opt/puppetlabs/puppet/bin/gem install r10k

	# download external puppet modules
	cd $DIR
	sudo /opt/puppetlabs/puppet/bin/r10k puppetfile install
}

maprbox_setup() {
	DIR=$(dirname $0)
	ENVIRON=production
	sudo /opt/puppetlabs/bin/puppet apply \
		--modulepath $DIR/modules/:$DIR/external \
		--hiera_config $DIR/hiera.yaml \
		--environmentpath=$DIR/environments \
		--environment=$ENVIRON \
		$DIR/environments/$ENVIRON/manifests/default.pp
}

maprbox_start() {
	sudo systemctl daemon-reload
	sudo systemctl start mapr-zookeeper && systemctl start mapr-warden
}

maprbox_stop() {
	sudo systemctl daemon-reload
	sudo systemctl stop mapr-warden && systemctl stop mapr-zookeeper
}

maprbox_restart() {
	sudo systemctl daemon-reload
	sudo systemctl stop mapr-warden && systemctl stop mapr-zookeeper && \
	sudo systemctl start mapr-zookeeper && systemctl start mapr-warden
}

maprbox_up() {
	maprbox_init && maprbox_setup && maprbox_start
}

maprbox_remove() {
	sudo yum erase -y mapr-* && sudo rm -fr /opt/mapr
}

maprbox_clean() {
	maprbox_stop && maprbox_remove
}


##### ##### main ##### #####

if [ $# -eq 0 ]; then
	help
	exit 1
fi

commandList=(help init setup start stop restart remove up clean)
command=$1
if [[ " ${commandList[*]} " == *" $command "* ]]; then
    maprbox_$command
else
	echo Error: invalid command: $command
	echo
	help
fi
